package_assets:         on           # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on           # (on, off)
gzip_assets:            off          # (on, off)
#template_function:      _.template  # (defaults to the built-in micro-templating)
#package_path:           packages    # (defaults to assets)
#javascript_compressor:  closure     # (yui, closure)
#compressor_options:
#  compilation_level: ADVANCED_OPTIMIZATIONS

javascripts:
  links:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
  tasks:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js

stylesheets:
  links:
    - public/stylesheets/links.css
  tasks:
    - public/stylesheets/tasks.css